- hosts: ansible
  become: yes
  roles:
    - ansible

- hosts: jenkins, docker, monitoring
  become: yes
  roles:
    - docker

- hosts: jenkins
  become: yes
  roles:
    - jenkins_master

- hosts: ansible, docker
  become: yes
  roles:
    - jenkins_client