---
  - name: Set Jenkins IP as a fact
    set_fact:
      jenkins_ip: "{{ ansible_host }}"

  - name: Install Docker
    apt:
      name: docker.io
      state: present

  - name: Create /var/jenkins_home
    file:
      name: /var/jenkins_home
      state: directory

  - name: Create /var/jenkins_home/casc_configs
    file:
      name: /var/jenkins_home/casc_configs
      state: directory

  - name: Add NFS export to fstab file
    ansible.builtin.lineinfile:
      path: /etc/fstab
      line: "{{ nfs_ip }}:/{{ export_directory }} /var/jenkins_home nfs defaults 0 0"
      create: yes

  - name: Apply mounts
    shell: systemctl daemon-reload && mount -a

  - name: Set directory permissions
    shell: chown -R 1000:1000 /var/jenkins_home

  - name: Copy JCasC YAML file to host
    copy:
      src: "{{ role_path }}/files/jenkins.yaml"
      dest: /var/jenkins_home/casc_configs/jenkins.yaml
      owner: 1000
      group: 1000

  - name: Run Jenkins Container
    docker_container:
      name: jenkins
      image: jenkins/jenkins
      state: started
      restart_policy: always
      ports:
        - "8080:8080"
      volumes:
        - /var/jenkins_home:/var/jenkins_home
        - /var/jenkins_home/casc_configs:/var/jenkins_home/casc_configs
      env:
        CASC_JENKINS_CONFIG: /var/jenkins_home/casc_configs/jenkins.yaml

  - name: Wait for Jenkins to start
    uri:
      url: "http://{{ ansible_host }}:8080/login"
      status_code: 200
      timeout: 60
    retries: 5
    delay: 10
    register: jenkins_status
    until: jenkins_status is succeeded
